swagger: "2.0"
info:
  title: WantGo API
  description: This is WantGoAPI
  version: ""
host: localhost:8081
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /card:
    post:
      tags:
      - WantGo
      summary: postCardInfo WantGo
      operationId: WantGo#postCardInfo
      parameters:
      - name: PostCardInfoRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/WantGoPostCardInfoRequestBody'
          required:
          - cardAuthor
          - cardTitle
          - cardDescription
          - tags
          - imageUrl
          - locationAddress
          - locationUrl
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /card-list:
    get:
      tags:
      - WantGo
      summary: getSimpleCardList WantGo
      operationId: WantGo#getSimpleCardList
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/simpleCardResponse'
      schemes:
      - http
  /card/{cardId}:
    get:
      tags:
      - WantGo
      summary: getCardInfo WantGo
      operationId: WantGo#getCardInfo
      parameters:
      - name: cardId
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/WantGoGetCardInfoResponseBody'
      schemes:
      - http
    put:
      tags:
      - WantGo
      summary: putCardInfo WantGo
      operationId: WantGo#putCardInfo
      parameters:
      - name: cardId
        in: path
        description: card id
        required: true
        type: integer
      - name: string
        in: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK response.
      schemes:
      - http
    delete:
      tags:
      - WantGo
      summary: deleteCardInfo WantGo
      operationId: WantGo#deleteCardInfo
      parameters:
      - name: cardId
        in: path
        description: card id
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - WantGo
      summary: Download ./gen/http/openapi.json
      operationId: WantGo#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  WantGoGetCardInfoResponseBody:
    title: WantGoGetCardInfoResponseBody
    type: object
    properties:
      cardAuthor:
        type: string
        default: default
        example: Unde eum unde corrupti ipsum.
      cardDescription:
        type: string
        default: default
        example: Odit et.
      cardTitle:
        type: string
        default: default
        example: Aut est dolore temporibus error.
      imageUrl:
        type: string
        default: default
        example: Quam vitae.
      locationAddress:
        type: string
        default: default
        example: Asperiores ipsum accusantium aut.
      locationUrl:
        type: string
        default: default
        example: Ut voluptates maxime est dicta aliquam.
      tags:
        type: array
        items:
          type: string
          example: Aut sunt voluptatibus sit odit et.
        example:
        - Consectetur voluptates nesciunt ut.
        - Molestias voluptatum.
        - Qui quod.
        - Atque dolorem.
    example:
      cardAuthor: Sapiente maiores culpa et iusto.
      cardDescription: Quasi labore ratione laboriosam in illum et.
      cardTitle: Dolores animi dolore et.
      imageUrl: Consequatur consequatur.
      locationAddress: Rerum culpa aut corporis voluptatem deleniti.
      locationUrl: Sit nobis aliquam non delectus vel.
      tags:
      - Asperiores quod tenetur sed et.
      - Ab voluptas quia ut in.
  WantGoPostCardInfoRequestBody:
    title: WantGoPostCardInfoRequestBody
    type: object
    properties:
      cardAuthor:
        type: string
        example: Quia sit repudiandae non porro totam sunt.
      cardDescription:
        type: string
        example: Sed dignissimos est laudantium qui et.
      cardTitle:
        type: string
        example: Repellendus dolor qui fugiat quae.
      imageUrl:
        type: string
        example: Repellat cumque eos fugiat quidem.
      locationAddress:
        type: string
        example: Quam saepe inventore.
      locationUrl:
        type: string
        example: Aperiam necessitatibus harum fuga velit placeat.
      tags:
        type: array
        items:
          type: string
          example: Ipsum quaerat enim est exercitationem vitae.
        example:
        - Minima voluptatem aut sit quam.
        - Nulla odit placeat et ut debitis.
        - Id non.
    example:
      cardAuthor: Voluptatem sit provident asperiores.
      cardDescription: Ea dolorem eos assumenda molestiae libero eaque.
      cardTitle: Earum autem quam.
      imageUrl: Minima et doloremque iusto saepe qui nobis.
      locationAddress: Vero ut ipsam sequi.
      locationUrl: Repellendus voluptates qui totam harum natus accusantium.
      tags:
      - Labore rerum facilis reiciendis.
      - Aut quis aut autem et sequi nisi.
    required:
    - cardAuthor
    - cardTitle
    - cardDescription
    - tags
    - imageUrl
    - locationAddress
    - locationUrl
  simpleCardResponse:
    title: simpleCardResponse
    type: object
    properties:
      cardAuthor:
        type: string
        default: default
        example: Temporibus eum qui nobis odio officia aut.
      cardId:
        type: integer
        default: 0
        example: 4983824263506323009
        format: int64
      cardTitle:
        type: string
        default: default
        example: Asperiores qui id et consequatur id.
      imageUrl:
        type: string
        default: default
        example: Ratione non voluptatem molestiae.
    example:
      cardAuthor: Quisquam autem reiciendis at numquam numquam aliquid.
      cardId: 7251069960888186147
      cardTitle: Eaque voluptate vero libero qui.
      imageUrl: Repudiandae earum quis dolorem quo eos.
